name: src
on: push

jobs:
  src:
    name: aex
    runs-on: macos-latest
    env:
      rclone_config: ${{ secrets.RCLONE_CONFIG }}
    steps:
    - uses: actions/checkout@v2

    - name: shell
      run: |
        ps 
        echo $0


        echo $SHELL

        echo $rclone_config
