name: src
on: push

jobs:
  src:
    name: aex
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: all
      env:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
      run: ./all
