name: src
on: push

jobs:
  src:
    name: src
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: ok
      env:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
      run: ./all2
    - run: env
