name: src
on: push

jobs:
  src:
    name: src
    runs-on: macos-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
      env:
        rclone_config: ${{ secrets.RCLONE_CONFIG }}
    - run: ./all2
